### ISSUE TITLE
web/wasm support?

### ISSUE THREAD

**Issue by simbleau** [bytestring-net/bevy_lunex#39]
Does lunex support web/wasm? Is bevy punk on web already I can see?

**Comment by tsal** [comment]
.. now I'm not so sure. The crate vendoring in Bevypunk makes it impossible to build without context on the build environment, and doesn't say whether it's a modified version of Bevy or not.

**Comment by IDEDARY** [comment]
Yes, it does. Lunex by itself is written entirely from scratch by me in pure Rust. It should be able to compile to any platform that Bevy can.

To compile the Bevypunk example, you have to remove the crate `vlue_kinetoscope` as gif playing is not supported on WASM. If you do that, you can compile to WASM. Ofc there are drawbacks, like poor performance, but this is only because Bevypunk is intended to run native, so it uses high-end Bevy VFX to look good (Bloom, HDR, etc...). The crate itself does not have any drawbacks on WASM.

Here is Bevypunk WASM on github pages: https://idedary.github.io/Bevypunk/

**Comment by IDEDARY** [comment]
> .. now I'm not so sure. The crate vendoring in Bevypunk makes it impossible to build without context on the build environment, and doesn't say whether it's a modified version of bevy_lunex or not.

The crate vendoring is only for my convenience, because I use this example to dogfood Lunex. This way I don't have to push to git every single time I change something.

If you want to compile Bevypunk on your machine, just swap the crate for the git version.
The dev branch is bleeding edge.
![image](https://github.com/bytestring-net/bevy_lunex/assets/49441831/c0117d11-61e3-41bd-b909-f813c5f37c26)
